// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MasterMessage — команда от master к slave.
type MasterMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectionUp   bool                   `protobuf:"varint,1,opt,name=direction_up,json=directionUp,proto3" json:"direction_up,omitempty"` // true = вверх (180°), false = вниз (0°)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMessage) Reset() {
	*x = MasterMessage{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMessage) ProtoMessage() {}

func (x *MasterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMessage.ProtoReflect.Descriptor instead.
func (*MasterMessage) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *MasterMessage) GetDirectionUp() bool {
	if x != nil {
		return x.DirectionUp
	}
	return false
}

// SlaveMessage — ответ от slave к master.
type SlaveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"` // подтверждение выполнения команды
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlaveMessage) Reset() {
	*x = SlaveMessage{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlaveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveMessage) ProtoMessage() {}

func (x *SlaveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveMessage.ProtoReflect.Descriptor instead.
func (*SlaveMessage) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *SlaveMessage) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\acontrol\"2\n" +
	"\rMasterMessage\x12!\n" +
	"\fdirection_up\x18\x01 \x01(\bR\vdirectionUp\"2\n" +
	"\fSlaveMessage\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2T\n" +
	"\fServoControl\x12D\n" +
	"\rCommandStream\x12\x15.control.SlaveMessage\x1a\x16.control.MasterMessage\"\x00(\x010\x01B&Z$github.com/novozhenin/practic/pkg/pbb\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_control_proto_goTypes = []any{
	(*MasterMessage)(nil), // 0: control.MasterMessage
	(*SlaveMessage)(nil),  // 1: control.SlaveMessage
}
var file_proto_control_proto_depIdxs = []int32{
	1, // 0: control.ServoControl.CommandStream:input_type -> control.SlaveMessage
	0, // 1: control.ServoControl.CommandStream:output_type -> control.MasterMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
