// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/control.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServoControl_CommandStream_FullMethodName = "/control.ServoControl/CommandStream"
)

// ServoControlClient is the client API for ServoControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServoControl — сервис управления сервоприводом.
// Master является gRPC-сервером, slave подключается как клиент.
type ServoControlClient interface {
	// CommandStream — двунаправленный поток.
	// Master отправляет команды, slave отправляет подтверждения.
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SlaveMessage, MasterMessage], error)
}

type servoControlClient struct {
	cc grpc.ClientConnInterface
}

func NewServoControlClient(cc grpc.ClientConnInterface) ServoControlClient {
	return &servoControlClient{cc}
}

func (c *servoControlClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SlaveMessage, MasterMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServoControl_ServiceDesc.Streams[0], ServoControl_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SlaveMessage, MasterMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServoControl_CommandStreamClient = grpc.BidiStreamingClient[SlaveMessage, MasterMessage]

// ServoControlServer is the server API for ServoControl service.
// All implementations must embed UnimplementedServoControlServer
// for forward compatibility.
//
// ServoControl — сервис управления сервоприводом.
// Master является gRPC-сервером, slave подключается как клиент.
type ServoControlServer interface {
	// CommandStream — двунаправленный поток.
	// Master отправляет команды, slave отправляет подтверждения.
	CommandStream(grpc.BidiStreamingServer[SlaveMessage, MasterMessage]) error
	mustEmbedUnimplementedServoControlServer()
}

// UnimplementedServoControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServoControlServer struct{}

func (UnimplementedServoControlServer) CommandStream(grpc.BidiStreamingServer[SlaveMessage, MasterMessage]) error {
	return status.Errorf(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedServoControlServer) mustEmbedUnimplementedServoControlServer() {}
func (UnimplementedServoControlServer) testEmbeddedByValue()                      {}

// UnsafeServoControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServoControlServer will
// result in compilation errors.
type UnsafeServoControlServer interface {
	mustEmbedUnimplementedServoControlServer()
}

func RegisterServoControlServer(s grpc.ServiceRegistrar, srv ServoControlServer) {
	// If the following call pancis, it indicates UnimplementedServoControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServoControl_ServiceDesc, srv)
}

func _ServoControl_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServoControlServer).CommandStream(&grpc.GenericServerStream[SlaveMessage, MasterMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServoControl_CommandStreamServer = grpc.BidiStreamingServer[SlaveMessage, MasterMessage]

// ServoControl_ServiceDesc is the grpc.ServiceDesc for ServoControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServoControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.ServoControl",
	HandlerType: (*ServoControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _ServoControl_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/control.proto",
}
